project:
  type: website

website:
  title: "CRUSE: Cycle Route Uptake and Scenario Estimation"
  navbar:
    left:
      - href: paper.qmd
        text: "Cruse to safe cycling in Ireland: paper"


format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto