project:
  render:
    - paper.qmd

website:
  title: "CRUSE"
  navbar:
    left:
      - href: paper.qmd
        text: "Cruse to safe cycling in Ireland: full paper"
      - href: https://cruse.bike
        text: "CRUSE web application"

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto