---
format: pdf
title: "Cover letter"
bibliography: references.bib
---

```{=html}
<!-- Cover letter file, answering the following questions:

    1–2 sentences about the importance of the manuscript.
    1–2 sentences about the experience the author group has on the topic (for example, previous publications).
    1–2 sentences about the (expected) clinical impact of the manuscript. -->
```
Dear Editor,

We are submitting our manuscript entitled "CRUSE to Safe Cycling in Ireland: An Open Source Tool to Support Active Travel" for consideration for publication in the European Transport Research Review, as part of a **Full Paper Submission for TRA 2024 (note: this option was not available the dropdown menu in the Thematic Series question, please ensure it is in the correct category)**.
It has a word count of 4,721, excluding references.

Please see the full list of authors and the abstract in the title page below.
The manuscript describes the development of an open source tool to support active travel in Ireland.
The paper describes the design, features and potential uses of the CRUSE Tool.
We believe that the paper is important because it marks a substantial step forward in the development of open source tools to support active travel.
The work presented goes substantially beyond previously published research such as the Propensity to Cycle Tool for England and Wales.

The Tool itself is important, providing the first comprehensive evidence base on cycling across Ireland.
The evidence is actionable, provided for free to all stakeholders in the transport planning process, with information on cycling potential and cycle friendliness down to the segment level nationwide.
We believe that our experiences developing the tool will be of use to others tasked with investing in cost effective cycle infrastructure.
Furthermore, and unusually for this kind of tool, a major policy driver was road safety: a key output of the tool is estimates of baseline levels of cycling, which can be used to generate estimates of road safety levels in units of killed or seriously injured casualties per billion km (KSI/bkm).

As a group we have wide experience in this space, as highlighted by the below selection of our previous publications:

-   A paper on cycling safety based on route network analysis [@meade2018]

-   Methods enabling inequalities to be accounted for in cycle network analysis and design [@mahfouz]

-   Methods enabling accurate modeling and effective visualization of origin-destination data and route networks [@morgan2020; @lovelace2022]

-   Analysis of infrastructure preferences for cycling in Ireland [@caulfield2012]

-   Papers describing previous approaches to developing strategic cycle network planning tools [@lovelace2017]

We expect the manuscript will have the following impacts:

-   Highlight the open availability of the CRUSE tool to stakeholders in Ireland, increasing its use, leading to more evidence-based and likely more effective network level designs, accounting for trade-offs between investment in 'fast' vs 'quiet' networks

-   Increase awareness of open evidence to support effective and data-driven investment in and planning for cycling internationally

-   Provide information and inspiration to researchers and other stakeholders to imagine, explore, and in some cases invest time in developing new strategic cycle network planning tools

All the best,

Robin Lovelace on behalf of all authors:

Robin Lovelace (University of Leeds, r.lovelace@leeds.ac.uk)

Joey Talbot (University of Leeds, J.D.Talbot@leeds.ac.uk)

Eugeni Vidal-Tortosa (University of Leeds, E.VidalTortosa@leeds.ac.uk)

Hussein Mahfouz (University of Leeds, tshma@leeds.ac.uk)

Elaine Brick (AECOM, elaine.brick@aecom.com)

Peter Wright (AECOM, peter.wright1@aecom.com)

Gary O'Toole (AECOM, Gary.OToole@aecom.com)

Dan Brennan (Transport Infrastructure Ireland, Dan.Brennan@tii.ie)

Suzanne Meade (Transport Infrastructure Ireland, Suzanne.Meade@tii.ie)



# Declarations

## Availability of data and material {.unnumbered}

Data was obtained from the Central Statistics Office (CSO) and Transport Infrastructure Ireland (TII) under license and cannot be shared publicly.
The code used to generate the results presented in this paper is available <!-- at https://github.com/cruse-bike. --> \[To be added after paper is accepted.\]

## Funding {.unnumbered}

The work was funded by Transport Infrastructure Ireland (TII).

## Acknowledgements {.unnumbered}

Thanks to Paul MacDonald and Donal Hodgins (Kildare County Council), for testing early versions of the tool and for their input into the project.
Thanks to Ciaran Maguire, Catherine Swift, and others at AECOM for their input into the project.
Thanks to Martin Lucas-Smith and Simon Nutall from CycleStreets for their input into the project.

## Competing interests {.unnumbered}

The authors declare that they have no competing interests.

## Authors' contributions {.unnumbered}

RL led the development of the CRUSE Tool, with input from JT, EV, HM, EB, PW, GOT, DB, and SM.
SM instigated the project and coordinated its policy impact.
PW, EB and GOT provided project management and transport engineering expertise.

# References