---
title: "CRUSE to Safe Cycling in Ireland: An Open Source Methodology to Support Active Travel"
format: 
  html:
    output-file: index.html
  pdf:
    output-file: cruse-paper.pdf 
  gfm:
    output-file: README.md
number-sections: true
editor: 
  # render-on-save: true
  markdown: 
    wrap: sentence
---

## 10th Transport Research Arena, TRA 2024, Dublin, Ireland {-}

*Dr. Robin Lovelace (a), Dr. Joey Talbot (a), Dan Brennan (b), Dr. Suzanne Meade (b), Elaine Brick (c), and Peter Wright (d)*

a University of Leeds, Institute for Transport Studies, Leeds, LS2 9JT, United Kingdom, Leeds LS2 9J, UK.

b Transport Infrastructure Ireland, Parkgate Business Centre, Parkgate Street, Dublin 8, D08 DK10, Ireland.

c AECOM, Unit 6, Galway Technology Park, Parkmore, Galway, Ireland.

d AECOM, Winslade House, Winslade Park, Manor Drive, Clyst St Mary, EXETER, EX5 1FY, UK.

## Abstract {-}

Under the EU Road infrastructure safety management (RISM) directive, the National Road Safety Strategy (RSS), and the Climate Action Plan Transport Infrastructure Ireland (TII) has a remit for road safety and decarbonizing a predominantly road-based network in Ireland.
To address data needs for both safety and project evaluation on the National Road Network (NRN), the Cycle Route Uptake and Scenario Estimation (CRUSE) Tool was developed.
While cycling in Ireland represents only 3% of total modal share, with higher intensities in urban areas, the levels of cycling collisions are disproportionately high at 20% of all serious injuries and 7% of all fatalities.
If Ireland is to meet its climate and safety targets, data to establish baseline cycling levels and future cycling levels is needed.

Due to an absence of reliable data, particularly rural cycling levels, TII commissioned the Institute for Transport Studies (ITS) at the University of Leeds and AECOM to develop a new tool for this purpose.
ITS Leeds led the development of the PCT for England and Wales, which has "revolutionized the practice of strategic cycle planning nationally".
The tool is an open-source approach using recognized open-source methodology to enable planners, engineers, and other stakeholders to make evidence-based decisions for the NRN.
CRUSE is available at <https://cruse.bike/> and builds on the Propensity to Cycle Tool (PCT) for England and Wales.
CRUSE goes beyond the PCT in several important ways, higher resolution data, more trip types, including estimates for education, inter-urban, and recreational trips.
In addition to understanding cycling intensity, for asset planning and management purposes, the tool provides essential road safety information to enable reporting of disaggregate collision rates.

CRUSE is structured in a similar way to the traditional four-stage transport model, but its use of Open Street Map (OSM) data, used by [Cyclestreets.net](https://www.cyclestreets.net/) for routing, enables network quality to be assessed without costly surveys to record new infrastructure.
OSM tags generate "cycle friendliness" estimates of all links on the network, based on existing recorded infrastructure.
A range of networks is provided, highlighting routes for directness (Fastest) and "cycle friendliness" (Quietest).
It uses origin and destination data from the 2016 Census in combination with modeled demand data to estimate cycling levels and potential at the area, route, and network levels for each county in Ireland and offers estimates of the baseline level of cycling and several future scenario-based levels of cycling.

As countries, like Ireland, invest in cycling, the number of killed and seriously injured cyclists must reduce too.
The CRUSE Tool provides estimates of cycling potential and routing for each county in Ireland, and works in both urban and rural settings, to enable monitoring of cycling safety.
With growth in the E-bike market, the tool will help inform inter-urban and rural networks to support the transfer of trips to sustainable modes for longer journeys.
The CRUSE Tool methodology and findings are directly relevant to addressing the challenges and opportunities faced by other NRAs.
The datasets resulting from the project are open access and can be used by both non-experts and professionals.

**Keywords:** Cycling, Cycling Exposure, Open-source, Road Safety, Active Travel.