---
title: "CRUSE to Safe Cycling in Ireland"
subtitle: An Open Source Methodology to Support Active Travel
bibliography: bibliography.bib
csl: apa.csl
editor:
  markdown:
    wrap: sentence
number-sections: true

# # Uncomment for draft versions:
# format: 
#   html: default
#   docx: default

# # Uncomment for formatted version
# format:
#   elsevier-pdf:
#     keep-tex: true
#     journal:
#       name: Journal Name
#       formatting: preprint
#       model: 3p
#       cite-style: super

# # Uncomment the following line to produce the cover page
author:
  - name: Dr. Robin Lovelace
    email: r.lovelace@leeds.ac.uk
    corresponding: true
    affiliations:
      - name: University of Leeds
        address: Institute for Transport Studies, Leeds, LS2 9JT, United Kingdom
  - name: Dr. Joey Talbot
    affiliations:
      - name: University of Leeds
        address: Institute for Transport Studies, Leeds, LS2 9JT, United Kingdom
  - name: Eugeni Vidal Tortosa
    affiliations:
      - name: University of Leeds
        address: Institute for Transport Studies, Leeds, LS2 9JT, United Kingdom
  - name: Hussein Mahfouz
    affiliations:
      - name: University of Leeds
        address: Institute for Transport Studies, Leeds, LS2 9JT, United Kingdom
  - name: Elaine Brick
    affiliations:
      - name: AECOM
        address: Unit 6, Galway Technology Park, Parkmore, Galway, Ireland
  - name: Peter Wright
    affiliations:
      - name: AECOM
        address: Winslade House, Winslade Park, Manor Drive, Clyst St Mary, EXETER, EX5 1FY, UK
  - name: "Gary O'Tool"
    affiliations:
      - name: AECOM
        address: Winslade House, Winslade Park, Manor Drive, Clyst St Mary, EXETER, EX5 1FY, UK
  - name: Dan Brennan
    affiliations:
      - name: Transport Infrastructure Ireland
        address: Parkgate Business Centre, Parkgate Street, Dublin 8, D08 DK10, Ireland
  - name: Dr. Suzanne Meade
    affiliations:
      - name: Transport Infrastructure Ireland
        address: Parkgate Business Centre, Parkgate Street, Dublin 8, D08 DK10, Ireland
abstract: |
  Under the EU Road infrastructure safety management (RISM) directive, the National Road Safety Strategy (RSS), and the Climate Action Plan Transport Infrastructure Ireland (TII) has a remit for road safety and decarbonizing a predominantly road-based network in Ireland.

  To address data needs for both safety and project evaluation on the National Road Network (NRN), the Cycle Route Uptake and Scenario Estimation (CRUSE) Tool was developed.
  While cycling in Ireland represents only 3% of total modal share, with higher intensities in urban areas, the levels of cycling collisions are disproportionately high at 20% of all serious injuries and 7% of all fatalities.
  If Ireland is to meet its climate and safety targets, data to establish baseline cycling levels and future cycling levels is needed.

  Due to an absence of reliable data, particularly rural cycling levels, TII commissioned the Institute for Transport Studies (ITS) at the University of Leeds and AECOM to develop a new tool for this purpose.
  ITS Leeds led the development of the PCT for England and Wales, which has "revolutionized the practice of strategic cycle planning nationally".
  The tool is an open-source approach using recognized open-source methodology to enable planners, engineers, and other stakeholders to make evidence-based decisions for the NRN.
  CRUSE is available at <https://cruse.bike/> and builds on the Propensity to Cycle Tool (PCT) for England and Wales.
  CRUSE goes beyond the PCT in several important ways, higher resolution data, more trip types, including estimates for education, inter-urban, and recreational trips.
  In addition to understanding cycling intensity, for asset planning and management purposes, the tool provides essential road safety information to enable reporting of disaggregate collision rates.
  
  CRUSE is structured in a similar way to the traditional four-stage transport model, but its use of Open Street Map (OSM) data, used by [Cyclestreets.net](https://www.cyclestreets.net/) for routing, enables network quality to be assessed without costly surveys to record new infrastructure.
  OSM tags generate "cycle friendliness" estimates of all links on the network, based on existing recorded infrastructure.
  A range of networks is provided, highlighting routes for directness (Fastest) and "cycle friendliness" (Quietest).
  It uses origin and destination data from the 2016 Census in combination with modeled demand data to estimate cycling levels and potential at the area, route, and network levels for each county in Ireland and offers estimates of the baseline level of cycling and several future scenario-based levels of cycling.
  
  As countries, like Ireland, invest in cycling, the number of killed and seriously injured cyclists must reduce too.
  The CRUSE Tool provides estimates of cycling potential and routing for each county in Ireland, and works in both urban and rural settings, to enable monitoring of cycling safety.
  With growth in the E-bike market, the tool will help inform inter-urban and rural networks to support the transfer of trips to sustainable modes for longer journeys.
  The CRUSE Tool methodology and findings are directly relevant to addressing the challenges and opportunities faced by other NRAs.
  The datasets resulting from the project are open access and can be used by both non-experts and professionals.
keywords: 
  - Cycling
  - Open-source
  - Road Safety
  - Active Travel
date: last-modified
---

{{< pagebreak >}}

# Introduction

Transport kills.
Transport systems are a major contributor to climate change, a leading cause of premature death and injury due to road traffic collisions, and a substantial cause of air pollution inhaled by citizens in many urban areas.
Transport policies therefore have great potential to decarbonize economies, improve public health, and save lives.

Transport is responsible for 23% of global emissions, 70% of which is from road transport, nearly half of which (around 10% of global emissions) is from passenger cars [@jaramillo2022].
The transport system encourages, enables and in some cases enforces unsustainable lifestyles, including over-consumption of goods due to excessive mobile storage space and dependency on services that are only accessible by car due to land use plans that have built up around roads [@gray2001; @shergold2012; @motte-baumvol2010].

Recognizing the growing evidence of such impacts of poorly designed and performing transport systems, governments in many countries have set targets and taken actions.
In the context of climate, road safety and physicial inactivity crises, policies to improve transport systems can be classified according to the 'Avoid-Shift-Improve' (ASI) framework [@jaramillo2022].
The framework highlights the importance of demand reduction (*avoid*ing unnecessary trips), in addition to mode *shift* and *improvement* of existing energy converters, in that order.

Uptake of cycling, the main topic of this paper, should be seen in this broader context of transport decarbonisation [@brand2020] and sustainable mobility [@burns2013].
Although cycling uptake appears on the surface to only relate to the 'shift' part of the ASI framework, closer consideration of the knock-on impacts of cycling uptake shows that it can also help avoid unnecessary trips [@nello-deakin2020].
The rapid uptake of highly efficient e-bikes can also be seen as an improvement on most electric vehicles, which are too heavy and expensive to be a sustainable alternative and could in fact delay the transition away from car dependency and inadvertently enable "high travel lock-in" [@anable2019].

At the European level, the European Union has set a target of reducing greenhouse gas emissions by 55% by 2030, compared to 1990 levels, and to achieve 'net-zero' by 2050.\[\^1\] Regarding road traffic casualties, another deadly consequence of inefficient transport systems, the Road Infrastructure Safety Management (RISM) directive (2008/96/EC) requires member states to implement a road safety management system (RSMS) for all public roads.
Specifically, "Member States shall ensure that the ranking of high accident concentration sections and the network safety ranking are carried out".[^1]
Given that 'safety' in this context is usefully quantified as the number of people killed and seriously injured (KSI) per distance travelled, the directive requires estimation of distance travelled by mode, down to the road link level.
For cycling, on which there is a paucity of data, this is a major challenge.

[^1]: https://eur-lex.europa.eu/legal-content/EN/TXT/?u
    ri=celex%3A32008L0096

In Ireland, the Road Safety Authority (RSA) has set the target of halving the number of road traffic deaths and serious injuries by 2030.\[\^3\] Doing so while simultaneously enabling rapid uptake of active modes will require key active travel routes to be identified and improved.

<!-- \[Gary, Suzanne, others input here please.\] -->

It was in this context that TII commissioned the Cycle Route Uptake and Scenario Estimation (CRUSE) project.
Based on the Propensity to Cycle Tool (PCT) for England and Wales [@lovelace2017], the CRUSE tool was developed to provide evidence on current cycling levels and future cycling potential nationwide across Ireland.

The rest of paper is structured as follows.
In @sec-methods, we outline the methods used to generate the evidence presented in the CRUSE tool for Ireland.
In @sec-results, we present the results of the CRUSE tool, including estimates of current cycling levels and future cycling potential at the national, regional and local levels.
In @sec-discussion, we discuss the implications of the results for policy and practice.
In @sec-conclusions, we conclude the paper.

# Methods {#sec-methods}

\[Should this bit go in a subsection in the Introduction rather than in the methods?
(RL)\]

The methods used to generate the evidence presented in the CRUSE tool for Ireland build on previous work, particularly the Propensity to Cycle Tool (PCT), which was originally developed for the UK's Department for Transport and which is publicly available at www.pct.bike [@lovelace2017].
The PCT approach has had major policy impacts, as outlined in Research Excellence Framework (REF) impact case studies submitted by the University of Leeds and the University of Westminster, which demonstrate that the tool "revolutionised strategic cycle planning in England and Wales"[^2] by overcoming the barriers to cycling investment imposed by lack of evidence on cycling potential[^3]
.

[^2]: See REF Impact Case Study "Cycle network policy, planning and investment transformed by the Propensity to Cycle Tool" at [results2021.ref.ac.uk](https://results2021.ref.ac.uk/impact/847d1191-7f25-46ba-a399-b481125edc8f) submitted by the University of Leeds.

[^3]: See the REF Impact Case Study "Creating Step Changes in Cycling Policy and Infrastructure Planning across the UK" at [results2021.ref.ac.uk](https://results2021.ref.ac.uk/impact/4BBF3436-FD10-4C75-9791-F5E98AB4411B) submitted by the University of Westminster.

The first version of the PCT was based on current and future potential uptake of cycling for single stage *travel to work* at desire line, zone, route, and route network levels [@lovelace2016].
It was launched in April 2017 as the government-endorsed tool for strategic cycle network planning, as part of the Cycling and Walking Investment Strategy [@cycling2017].
Extensions of the PCT approach have included estimation of benefits at the individual level [@woodcock2018], addition of travel to school network [@goodman2019], and improved modelling of impacts on health, environmental and distributional outcomes [@woodcock2021].
Initially developed just for England, the PCT was extended to cover all of Wales (for commuter data only) in 2018.

The PCT approach has been applied in other countries, including Ireland (the topic of this paper), Scotland, and Portugal.
In Portugal, a strategic cycle network planning tool was developed based on PCT methods, for the Lisbon metro region.
The resulting open and publicly available available evidence is available in an interactive web application hosted at [biclar.tmlmobilidade.pt](https://biclar.tmlmobilidade.pt) [@felix2023].
The 'biclaR' project included estimation of impacts, using the World Health Organisation (WHO) 'HEAT for Cycling' tool[^4].
biclaR extended the approach with an 'intermodality' scenario that combines cycling with currently available public transit options based on General Transit Feed Specification (GTFS) data.

[^4]: See the Health economic assessment tool for walking and cycling at [www.heatwalkingcycling.org](https://www.heatwalkingcycling.org/#homepage).

Despite these advances, the PCT approach outlined in previous research paper had limitations:

-   Limited coverage of trip purposes beyond travel to work and school
-   Low resolution of data, with routes starting and ending in administrative zone centroids
-   A web interface that was not user-friendly or intuitive

The CRUSE project addressed these limitations as outlined in this paper.

Bit on Jittering [@lovelace2022]

# Results {#sec-results}

National planning

Regional

Local

# Discussion {#sec-discussion}

# Conclusions {#sec-conclusions}

# List of abbreviations

# Declarations

## Availability of data and material {.unnumbered}

Data was obtained from the Central Statistics Office (CSO) and Transport Infrastructure Ireland (TII) under license and cannot be shared publicly.
The code used to generate the results presented in this paper is available at https://github.com/cruse-bike.

## Funding {.unnumbered}

The work was funded by Transport Infrastructure Ireland (TII).

## Acknowledgements {.unnumbered}

Thanks to Paul MacDonald and Donal Hodgins (Kildare County Council), for testing early versions of the tool and for their input into the project.
Thanks to Ciaran Maguire, Catherine Swift, and others at AECOM for their input into the project.

## Competing interests {.unnumbered}

The authors declare that they have no competing interests.

## Authors' contributions {.unnumbered}

RL led the development of the CRUSE tool, with input from JT, EV, HM, EB, PW, GOT, DB, and SM.
SM instigated the project and coordinated its policy impact.
PW, EB and GOT provided project management and transport engineering expertise.